In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv(r"C:\Users\solan\OneDrive\Desktop\NekoAI\NekoAI-AI-Companion\dataset\raw\student_productivity_distraction_dataset_20000.csv")

In [4]:
df.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [5]:
df.drop("student_id", axis=1, inplace=True)

In [6]:
df.head()

,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

ML models understand only numbers

In [7]:
encoder = LabelEncoder()
df["gender"] = encoder.fit_transform(df["gender"])

In [8]:
df.head()

,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,23,0,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,20,1,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,29,0,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,27,0,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,24,1,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    20000 non-null  int64
 1   gender                 20000 non-null  int64
 2   study_hours_per_day    20000 non-null  float64
 3   sleep_hours            20000 non-null  float64
 4   phone_usage_hours      20000 non-null  float64
 5   social_media_hours     20000 non-null  float64
 6   youtube_hours          20000 non-null  float64
 7   gaming_hours           20000 non-null  float64
 8   breaks_per_day         20000 non-null  int64
 9   coffee_intake_mg       20000 non-null  int64
 10  exercise_minutes       20000 non-null  int64
 11  assignments_completed  20000 non-null  int64
 12  attendance_percentage  20000 non-null  float64
 13  stress_level           20000 non-null  int64
 14  focus_score            20000 non-null  int64
 15  final_grade            20000 non-null  float64
 16  productivity_score     20000 non-null  float64
dtypes: float64(9), int64(8)
memory usage: 2.6 MB

In [10]:
X = df.drop("productivity_score", axis=1)
y = df["productivity_score"]

In [11]:
print(X.shape)
print(y.shape)

(20000, 16)
(20000,)

#Split Dataset for Traning and Testing

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16000, 16)
(4000, 16)
(16000,)
(4000,)

In [14]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [15]:
print(X_train[:5])

[[ 1.32663025  2.53606691 -0.25309735  0.53830331 -1.37905973  1.39900544
   0.4704985   0.11749473 -1.37900724  0.04845795  1.21607664  0.77971873
  -0.98658908  0.18174438  0.17648545  0.00595212]
 [-1.3377875  -0.98166786  0.98242056  0.8136638  -0.61067895  0.65062233
   1.04817028  0.3194482   0.36353863  0.84162438  1.5909828   1.29864472
   1.0118997  -1.56181606  0.22592634 -0.73481863]
 [-1.07134572  0.77719952  0.29359199  1.23162167 -0.93436691  0.46893394
   1.21569509  0.44062028 -0.63220187  0.00671234 -0.77380993 -0.08515792
   0.1433412   0.87916856 -0.36736438  0.12334202]
 [-0.53846217 -0.98166786 -1.40478955  0.75957513 -1.18242685 -1.28306122
  -1.64955693  1.30036507 -0.88113699 -1.35001971  1.44678812 -1.64193588
   1.00960193 -0.16696771 -1.50450492  0.66807741]
 [ 0.52730492  0.77719952  1.46350717  0.43012598  1.3374991   0.52517082
   0.25675994  1.38691656  0.86140888  1.300826    0.17787495  1.29864472
  -1.27725747 -0.16696771 -1.35618224 -1.22982235]]

Save the Scaler

In [22]:
import joblib
joblib.dump(scaler, r"C:\Users\solan\OneDrive\Desktop\NekoAI\NekoAI-AI-Companion\ml_model\models\pipeline.pkl")

['C:\\Users\\solan\\OneDrive\\Desktop\\NekoAI\\NekoAI-AI-Companion\\ml_model\\models\\pipeline.pkl']

In [23]:
import pickle

# In 02_Data_Preprocessing.ipynb
with open(r'C:\Users\solan\OneDrive\Desktop\NekoAI\NekoAI-AI-Companion\ml_model\models\pipeline.pkl', 'wb') as f:
    pickle.dump((X_train, X_test, y_train, y_test), f)

In [24]:
from sklearn.preprocessing import StandardScaler
import pickle

scaler = StandardScaler()
scaler.fit(X_train)

# Save scaler
with open(r"C:\Users\solan\OneDrive\Desktop\NekoAI\NekoAI-AI-Companion\ml_model\models\scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)